apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  nginx.conf: |
    events {}

    http {
      server {
        listen 80;

        location /product/ {
          proxy_pass http://product-service:8001/;
        }

        location /customer/ {
          proxy_pass http://customer-service:8002/;
        }

        location /cart/ {
          proxy_pass http://cart-service:8003/;
        }

        location /order/ {
          proxy_pass http://order-service:8004/;
        }

        location /delivery/ {
          proxy_pass http://delivery-service:8005/;
        }
      }
    }